ACCESS_TOKEN = 'API TOKEN'
WEBHOOK_URL = 'NGROK LINK'
TELEGRAM_BASE = 'https://api.telegram.org/bot{}'.format(ACCESS_TOKEN)
TELEGRAM_WEBHOOK_URL = TELEGRAM_BASE + '/setWebhook?url={}/hook'.format(WEBHOOK_URL)
FUGLE_API_TOKEN = 'FUGLE API'
OLD_ACCESS_TOKEN = 'TEMPERORY API TOKEN'
